IBM/cloudant-node-sdk

- package-lock.json
- package.json
* IAM Authenticator: add support for optional 'scope' property
> Update core version to 2.5.0

- package-lock.json
- package.json
Fixes: #15 
An axios upgrade that enables transparent gzip response decoding.
> Update core version to 2.6.0

- package.json
style: correct whitespace in package.json
> style: correct whitespace in package.json

- package-lock.json
- package.json
`ibm-cloud-sdk-core` dependency is at version 2.6.0
- `ibm-cloud-sdk-core` dependency updated to 2.7.0
- Only get 2.7.x patches using `~`
https://github.com/IBM/node-sdk-core/releases/tag/v2.7.0
> Update core dependency to 2.7.0

- README.md
- test/examples/src/js/GetInfoFromExistingDatabase.js
- test/examples/src/ts/GetInfoFromExistingDatabase.ts
Change var name in `GetInfoFromExistingDatabase.js`, `GetInfoFromExistingDatabase.ts` and README examples from `examplesClient` to `client` for consistency with the rest of the examples.
> docs: Update var name in GetInfoFromExistingDatabase examples

- package-lock.json
- package.json
- scripts/report_integration_test.js
- test/examples/src/js/CreateOutputs.js
- test/integration/cloudant.integration.test.js
- test/integration/readme.integration.test.js
- test/resources/auth-helper.js
Gather dependabot PRs into one PR.
This PR has all the commits from dependabot PRs:
https://github.com/IBM/cloudant-node-sdk/pull/36 -> @semantic-release/changelog (dev)
https://github.com/IBM/cloudant-node-sdk/pull/35 -> @types/node
https://github.com/IBM/cloudant-node-sdk/pull/34 -> jest (dev)
https://github.com/IBM/cloudant-node-sdk/pull/33 -> codecov (dev)
https://github.com/IBM/cloudant-node-sdk/pull/32 -> prettier (dev)
This PR bumps the dependencies to the versions mentioned in the commit messsages.
> Dependabot cherry pick

- package-lock.json
- package.json
Closes: #61 
Closes: #62 
Closes: #63 
Closes: #64 
Closes: #65 
Updated the following dependencies:
* highlight.js from 10.4.0 to 10.4.1 
* eslint from 7.14.0 to 7.15.0 
* eslint-plugin-prettier from 3.1.4 to 3.2.0
* eslint-config-prettier from 6.15.0 to 7.0.0
* @types/jest from 26.0.15 to 26.0.16
> Dependabot dependency updates - collection

- .eslintignore
- .eslintrc.js
- package-lock.json
Generated files are excluded from `checkstyle` header checks. This PR includes them so that they are verified.
> Add header checks for generated files

- package-lock.json
As @bessbd had in one of his previous PRs the `package-lock.json` file has some `"optional": true` parameters that are necessary for publishing a new tag.
> Refresh package-lock.json file with optionals

- scripts/typedoc/generate_typedoc.sh
Relates to: sdks/doc-generation
No typedoc is available.
This  script will generate typedoc.
To generate the document you need to call from the project root: `./scripts/typedoc/generate_typedoc.sh`
The generated doc is published on GH pages, that is availanle from here: https://ibm.github.io/cloudant-node-sdk/docs/test-doc/
The doc publish process is not merged yet. Here you can also review it: https://github.com/IBM/cloudant-node-sdk/pull/98
This PR contains only the typedoc generation script.
> Update typedoc generator script

- KNOWN_ISSUES.md
- lib/cloudantBaseService.ts
- test/unit/cloudantBaseService.test.js
Fixes: #176 
Setting `false` in `setEnableGzipCompression` has no effect.
Setting `false` in `setEnableGzipCompression` will disable gzip compression for requests.
> Fix gzip compression option

- .travis.yml
Relates to: #145 
Currently node 15 is not tested.
Node 15 is added to the testing CI.
> Add Node 15 to tested node versions

- .travis.yml
- package-lock.json
- package.json
Currently we are not getting any benefit from the `codecov` integration and  due to [a recent security incident](https://about.codecov.io/security-update/?utm_medium=email&utm_source=marketo&ajs_uid=&ajs_event=Clicked%20Email&mkt_tok=MzMyLUxWWC03NDEAAAF8dJnGkNG_ojrjdXL2M-fOtB8t5IIphrIeLMth6mxIfuhPHB7b_FDof-GXtPcIc5fc754EGZ-_sxnLPdyBwLd1yNBoppIr0iZuG9A5_FAL) we decided to remove it.
> ci: remove codecov install and execution

- .travis.yml
- README.md
- package.json
Relates to: #254 
Currently Node 10 is supported and 15 is also tested, 16 is not included.
Introduce Node 16 and remove 10 and 15 from supported versions.
`>=12` would allow to have 15 as node version, so better if it specified per versions.
> Add node 16 and remove 10 support

- README.md
Fixes #254
Automated PR triggered by new code generation.
Update generated source code
Generated SDK source code using:
- Generator version 3.30.0
- Specification version 1.0.0-dev0.0.35
- Automation (cloudant-sdks) version dbd1f78
> Update generated source code

- test/examples/src/js/UpdateDoc.js
- test/examples/src/ts/UpdateDoc.ts
Fixes: <! -- link to issue -->
Add stream handling examples in note comments to update document example.
> Add streaming notes to update example file

- auth/couchdbSessionAuthenticator.ts
- test/unit/couchdbSessionAuthenticator.test.js
The future version of the core will have an `authenticationType` function. We need to update our custom Authenticator implementations to implement this.
Getting the authentication type is not possible.
The new authenticationType method makes getting the authentication type possible.
> feat(auth): Add authenticationType to couchdbSessionAuthenticator

- KNOWN_ISSUES.md
CouchDB 3.2.0 contains the fix for gzipped `_session` requests.
Updated the minimum CouchDB version in the session auth statement.
> Update session auth statement in README

- test/unit/couchdbSessionAuthenticator.test.js
Test `test/unit/couchdbSessionAuthenticator.test.js` fails locally on a machine in none GMT time zone. The reason is that the test sets expiration time based on `new Date()` which returns date-time in the device local time while `tough-cookie` during date parse [assumes this time to be in UTC](https://github.com/salesforce/tough-cookie/blob/master/lib/cookie.js#L316). So depending on a local timezone expiration time "drifts".
This fix normalizes set expiration time to UTC.
Fixes: #620 
[Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commi …
> Normalize expiration time in session renewal test

- package-lock.json
Fix `node-fetch` severity vulnerability
> build(dev-deps): Fix node-fetch severity vulnerability

- .github/dependabot.yml
- package-lock.json
- package.json
The minimum Node version is 12.x so we should be "compiling" against Node types 12.x to make sure we don't use things we shouldn't. To keep pinned versions and get dependabot version updates except major we just need to tell dependabot to ignore majors.
> Update node version for @types/node

- package-lock.json
- package.json
- test/integration/readme.integration.test.js
The goal of this PR is to get rid of the `axios` dev dependency.
I used Node's `http` instead in the tests where wiremock was used.
> ci(dev-deps): remove axios

- package-lock.json
- package.json
The goal of this PR is to move dependencies that we use, but are installed from core into peerDependencies (tough-cookie, extend)
> Use peer dependencies

- lib/common.ts
- package.json
- test/unit/common.test.js
Normalize `User-Agent` header to match new sdks specs.
An example:
```
cloudant-node-sdk/0.0.25 (node.version=v16.13.1; os.name=darwin; os.version=20.6.0; os.arch=x64; lang=node.js;)
```
On 64 chars:
```
cloudant-node-sdk/0.0.25 (node.version=v16.13.1; os.name=darwi
```
> refactor: modify User-Agent header

- package-lock.json
- package.json
Bundle together latest dependabot updates to pass travis
Fixes: #731 #732 #733 #734 
> build(deps): Dependabot bundle

- test/examples/src/js/CreateDbAndDoc.js
- test/examples/src/js/DeleteDoc.js
- test/examples/src/js/GetInfoFromExistingDatabase.js
- test/examples/src/js/UpdateDoc.js
- test/examples/src/ts/CreateDbAndDoc.ts
- test/examples/src/ts/DeleteDoc.ts
- test/examples/src/ts/GetInfoFromExistingDatabase.ts
- test/examples/src/ts/UpdateDoc.ts
The goal of this PR is to improve the description of `_rev`/`rev` requirements for post/put document. I also fixed the ornamentation comment lines to 82 char length because I caught those not shared the same length. I also tried to explain where `_id`/`docId` is necessary similarly to `_rev`/`rev`.
I decided to use `/*...code is here...*/` for code comments and ornamentation lines before and after the explanation plus the commented out codes because with this way maybe the eyes can catch what belongs to what. Something like this:
```
// ========================================================================
// Note: the next code bla bla bla..:
/*
code is here
*/
// ========================================================================
```
❗ REVIEWERS ❗ 
Please read the `Other …
> docs: improve description of rev requirements for post/put document

- test/examples/output/CreateDbAndDoc.txt
- test/examples/src/js/CreateDbAndDoc.js
- test/examples/src/ts/CreateDbAndDoc.ts
I grabbed the commit [6a830ae](https://github.com/IBM/cloudant-node-sdk/pull/739/commits/6a830ae3b0d6305b3525ab22d411314a64f90a8e) to check this change together with that will green the pipeline.
Related to #737 
> docs: fix timestamps for README

- .travis.yml
ci: add 18 to travis matrix
Fixes: #799 
Tests run on Node 14, 16, 17
Tests run on Node 14, 16, 18
Getting Node 18 to work in travis required updating dist to `focal`.
> ci: add 18 to travis matrix

- package-lock.json
Update the `package-lock` dependency file to the latest compatible versions.
Fixes:
https://github.com/IBM/cloudant-node-sdk/security/dependabot/10
https://github.com/IBM/cloudant-node-sdk/security/dependabot/12
`package-lock` transient deps are a little stale.
`package-lock` is updated to the most recent compatible deps.
> ci(deps-dev): update package-lock deps

- .eslintignore
Exclude examples dir from linting
~Fixes: <! -- link to issue -->~
Prep work for adding `examples` directory with code snippets.
> Exclude examples dir from linting

- .github/workflows/test.yml
- scripts/setup_couch.sh
- scripts/setup_wiremock.sh
This is a test to evaluate the merit of switching from Travis to github actions for simple version matrix tests
> Update repo to use GH actions

- .github/workflows/test.yml
Disable persisting the actions token
`persist-credentials: true` the default for checkout action
`persist-credentials: false`
The actions don't need to run any other `git` commands.
>  Disable persisting the actions token

- .github/workflows/test.yml
> ci: add node 19 to test matrix

- package-lock.json
- package.json
- Bumps ibm-cloud-sdk-core from 3.2.1 to 4.0.0
- Bumps jest from 27.5.1 to 29.3.1
- Bumps ts-jest from 27.1.4 to 29.0.3
> build(deps): bump ibm-cloud-sdk-core to 4.0.0

- test/unit/cloudantBaseService.test.js
This PR meant to fix issue: _Objects should not be created to be dropped immediately without being used_
> fix(test): assert on mock

- package-lock.json
Fixes: CVE-2022-25881:
https://github.com/IBM/cloudant-node-sdk/blob/770d9ca4f3b9a6eb021a3d2b2a388e3f3b9ffefd/package-lock.json#L8210-L8211
https://github.com/IBM/cloudant-node-sdk/blob/770d9ca4f3b9a6eb021a3d2b2a388e3f3b9ffefd/package-lock.json#L8617-L8625
https://github.com/IBM/cloudant-node-sdk/blob/770d9ca4f3b9a6eb021a3d2b2a388e3f3b9ffefd/package-lock.json#L18502-L18503
https://github.com/IBM/cloudant-node-sdk/blob/770d9ca4f3b9a6eb021a3d2b2a388e3f3b9ffefd/package-lock.json#L18794-L18801
Since an automatic update could not fix the vulnerability, I had to recreate the `package-lock.json` file. I used `node=16.19.0` and `npm=8.19.3` because these are the …
> build: fix CVE-2022-25881

- .secrets.baseline
- package-lock.json
- package.json
Remove semantic-release dependencies
Semantic release is installed as part of the `devDependencies`.
Semantic release will not be installed as part of the `devDependencies`, instead it will be provided by the CI pipeline so that it is consistent with the other lang SDKs.
Note, secrets baseline is also updated.
> Remove semantic-release dependencies

- .github/workflows/static.yml
Use GHA to deploy to pages.
Classic pages deployment.
GitHub Actions pages deployment.
The classic deployment no longer supports symlinks, changing to actions will hopefully avoid the need to rework the way we link latest to the most recent tagged version.
> ci: typedoc pages deployment action

- .secrets.baseline
- package-lock.json
chore: update package-lock
Old deps forced by package-lock.
Latest in range deps.
Also updates `.secrets.baseline`
> chore: update package-lock

- cloudant/features/changesFollower.ts
- cloudant/features/changesParamsHelper.ts
- cloudant/features/changesResultItemStream.ts
- cloudant/features/changesResultIterator.ts
- cloudant/features/stream.ts
- lib/cloudantBaseService.ts
- package.json
- test/examples/src/features/js/initialize.js
- test/examples/src/features/js/start.js
- test/examples/src/features/js/startAndProcess.js
- test/examples/src/features/js/startOneOff.js
- test/examples/src/features/js/startOneOffAndProcess.js
- test/examples/src/features/js/stop.js
- test/examples/src/features/ts/initialize.ts
- test/examples/src/features/ts/start.ts
- test/examples/src/features/ts/startAndProcess.ts
- test/examples/src/features/ts/startOneOff.ts
- test/examples/src/features/ts/startOneOffAndProcess.ts
- test/examples/src/features/ts/stop.ts
- test/unit/features/changesFollower.test.js
- test/unit/features/changesParamsHelper.test.js
- test/unit/features/changesResultItemStream.test.js
- test/unit/features/changesResultIterator.test.js
- test/unit/features/mockErrors.js
- test/unit/features/testDataProviders.js
- test/unit/features/testMocks.js
- test/unit/features/testParams.js
- test/unit/features/testUtils.js
Add changes follower feature.
Users have to call `postChanges` repeatedly and handle various transient errors or disconnects.
The feature adds a helper to automatically paginate the changes feed and return the changes in a stream. It also suppresses transient exceptions and retries (though this can be disabled).
> feat: changes follower

- .github/workflows/test.yml
- package-lock.json
- package.json
Officially adds node 20 support
> Add node 20 support

- cloudant/features/changesResultIterator.ts
Resolve memory leak by ensuring all promises settled at end of request in changes follower.
Fixes: #1379
Memory leaks over time because the cancel token promise is never resolved, causing it's "paired" request in the `Promise.race` to be retained along with it's large response payload.
Ensure that the Promise.race promises are eligible for GC by making a new cancellable for each request and resolving it after the request.
The existing tests exercise this code. It …
> fix: ensure all promises settled at end of request

- package-lock.json
Clean-up 1 moderate severity vulnerability during `npm install` using `npm audit fix`
Fixes: i873
> build: cleanup package with npm audit fix

- package-lock.json
- package.json
Bump core to 4.2.1 to address CVE in axios
> build(deps): Bump ibm-cloud-sdk-core from 4.2.0 to 4.2.1

- cloudant/v1.ts
- package-lock.json
- package.json
- tsconfig.json
Switch to "es2022" for tsconfig, keep building in cjs for consistency 
> build: switch to es2022 in tsconfig

- .github/workflows/docs.yml
- .github/workflows/test.yml
We are getting deprecation warnings on our CI runs on using outdated actions. This update to fix that.
> ci(chore): update actions checkout and setup-node in github workflows

- .github/workflows/test.yml
Node's 22 (Upcoming LTS ) was released on Apr 24 as "current" version. This PR switches from node 21 to 22 in Github Actions test matrix.
> build: switch from node 21 to 22

- package-lock.json
- package.json
This adds new dev dep lib `@ibm-cloud/sdk-test-utilities` to allow migration to the latest generator
> chore: add dev dep @ibm-cloud/sdk-test-utilities

- package-lock.json
- package.json
This is taken out from https://github.com/IBM/cloudant-node-sdk/pull/1595.
> build(deps-dev): bump eslint-plugin-jsdoc from 48.10.1 to 48.11.0

- package.json
Update description with keywords
Fixes: part of s1012
Package metadata update
Add additional keywords for searching.
> chore: update package keywords

- .eslintrc.js
- package-lock.json
- package.json
Fixes: s1040
Applies ESLint ruleset from the archived Airbnb typescript base package on `*.ts` files.
Most places use equivalent ESLint rules based on Airbnb's base package, slightly modified by custom configurations from our offline chat on Friday.
> build: remove airbnb typescript ESLint configuration

- auth/sessionTokenManager.ts
- cloudant/v1.ts
- lib/cloudantBaseService.ts
- test/unit/sessionTokenManager.test.js
this change fixes gauge pipeline issues caused by recent generator change
> refactor: move setting of operation id for post session to SessionTokenManager

- cloudant/features/pagination/allDocsBasePageIterator.ts
- cloudant/features/pagination/basePageIterator.ts
- cloudant/features/pagination/findBasePageIterator.ts
- cloudant/features/pagination/keyPageIterator.ts
- cloudant/features/pagination/viewBasePageIterator.ts
- test/unit/features/pagination/bookmarkPageIterator.test.js
- test/unit/features/pagination/keyPageIterator.test.js
- test/unit/features/pagination/paginationTestHelper.ts
- test/unit/features/pagination/paramValidation.test.js
Various fixes for pagination
Fixes: s1188
**Note: An existing issue is [required](https://github.com/IBM/cloudant-python-sdk/blob/main/CONTRIBUTING.md#PRs) before opening a PR.**
The new pagination feature code (unreleased) from #1817 had a few bugs and missing features.
* `key` param was allowed for view-like pagers
* `skip` param set by user was not removed from subsequent pages
* Needed a safer solution if doc IDs are null or undefined on results that any code accessing them must not crash.
* Disallow `key` as an param for pagination
* Remove `skip` param from subsequent pages
* Add new tests …
> Pagination fixes

- package-lock.json
Bump brace-expansion to 1.1.12 as don eby `npm audit fix`
> build: bump brace-expansion to 1.1.12
