IBM/cloudant-node-sdk

.gitignore, package-lock.json, package.json
Make jest to run jest-junit as a results processor to generate junit reports in `test-reports` directory
No junit reports generated
`jest` generates junit reports in `test-reports` directory as a results processing step
=> ci: Generate tests runs' junit reports

.gitignore, package.json
Rename junit reports dir to match other sdks
junit reports saved in `test-reports` dir
junit reports saved in `junitreports` dir
=> ci: Rename junit reports dir

package-lock.json, package.json, test/unit/cloudantBaseService.test.js
fixes: #211 
Update existing test
IAM url in `Use basic authenticator` test contains the root path and operation suffix path (`/identity/token`).  This fails because of the [IAM url change in the latest node-sdk-core release](https://github.com/IBM/node-sdk-core/pull/125).
Update IAM url test variable to `https://iam.cloud.ibm.com`.
=> Update IAM url test variable

lib/cloudantBaseService.ts
Fixes: #210
gzip compression setting is explicitly added to base options.
This is fixed in `node-sdk-core` and we can now remove the workaround.
=> Revert workaround for gzip compression setting in base options

test/unit/sessionTokenManager.test.js
Fixes: #19 
Intermittently the unit test fails with the following error:
```
FAIL  test/unit/sessionTokenManager.test.js
262  ● SessionTokenManager tests › Test saveTokenInfo › Session token with expire time stamp
263
264    assert.strictEqual(received, expected)
265
266    Expected value to strictly be equal to:
267      2
268    Received:
269      1.7999999523162842
270
271      160 |       assert.strictEqual(Math.ceil(manager.refreshTime - dateNow / 1000), 8); …
```
=> Add round up to expire and refresh time difference check.

auth/couchdbSessionAuthenticator.ts, auth/sessionTokenManager.ts, test/unit/couchdbSessionAuthenticator.test.js
Fix the issue where, [when using `AUTH_TYPE=COUCHDB_SESSION`](https://github.com/IBM/cloudant-node-sdk#session-cookie-authentication), the renewed session cookies were purged by the third-party cookie store preventing sessions being renewed beyond one lifetime.
Fixes: #209 
Due to [tough-cookie's interpretation of the cookie spec](https://github.com/salesforce/tough-cookie/issues/154) cookie handling is different to those observed in browsers and most other …
=> 209 session renewal

package-lock.json
Fixes: -
- [] Bugfix
The `trim-off-newlines` package contains a vulnerability.
Remove `trim-off-newlines` package that has a vulnerability alert. Turned out there is no released fix yet.
However there is in fact a solution to avoid the vulnerability:
* Update `conventional-commits-parser` package from 3.2.1 to 3.2.2. 
Since this new version was released today, I created a new `package-lock.json` file.
I made the following actions:
`rm -fr ./node_modules …
=> Fix vulnerability in trim-off-newlines 

package.json
Remove Node 17 from list of supported engines.
Follow up from #538 #539
#539 went a little too far in adding this; whilst we test `17` to get ready for `18` it still shouldn't be listed as a supported engine.
As per https://github.com/IBM/cloudant-node-sdk#prerequisites the supported versions of Node are `12`, `14` or `16`.
These are the LTS versions at this time.
This is aligned with the policy outlined at https://nodejs.org/en/about/releases/#releases
>Production applications should only use Active LTS or Maintenance LTS releases.
By default this change will not prevent use on Node 17, but it …
=> build: remove node 17 from engines

scripts/typedoc/generate_typedoc.sh
This change fixes a problem introduced by a breaking change in typedoc 0.22 where default `entryPointStrategy` changed, leading for generated docs to omit `cloudant/v1` module.
Generation of docs for module `cloudant/v1` been omitted
Docs for module `cloudant/v1` properly generated.
=> Change default entry point strategy for typedoc

.secrets.baseline, lib/getAuthenticatorFromEnvCloudantExtension.ts, test/unit/getAuthenticatorFromEnvCloudantExtension.test.js
Support a env var name alias `AUTHTYPE` for `AUTH_TYPE` to keep core's compatibility
Env var of format `SERVICE_AUTHTYPE` is ignored and error thrown on missing required variable
Env var of format `SERVICE_AUTHTYPE` accepted as a valid variable same as `SERVICE_AUTH_TYPE`
=> Support alias env var AUTHTYPE

.travis.yml, package-lock.json
There was one vulnerability we were alerted by dependabot: https://github.com/IBM/cloudant-node-sdk/security/dependabot/package-lock.json/ansi-regex/open
This PR will fix that issue and also remove audit from our CI bc dependabot/GH security alerts has got this covered for us - and it is checking all the time (not just when we build).
1. There is one alert about `ansi-regex` for this repo.
2. Travis build warns about the vulnerabilities both for dev and prod deps.
1. Hopefully, the alert will disappear, since when I run `npm audit --production` 0 vulnerabilities are found:
```sh
$ npm audit …
```
=> Npm audit fixes

package-lock.json
When I was trying to run tests on my local machine I faced an issue:
* There was 1 high priority severity vulnerability for prod deps: `follow-redirects`
```sh
$ npm audit --production
follow-redirects  <1.14.7
Severity: high
Exposure of sensitive information in follow-redirects - https://github.com/advisories/GHSA-74fj-2j2h-c42q
$ npm audit fix --production
changed 1 package, and audited 96 packages in 6s
6 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
=> Fix package problems

.secrets.baseline, lib/cloudantBaseService.ts, test/unit/cloudantBaseService.test.js
`keepAlive` is [not on by default](https://github.com/IBM/node-sdk-core/blob/8b82f36bf6d4ac0163563ce3a10f0a395bd87627/test/unit/request-wrapper.test.js#L130) in `node-sdk-core` which means no connection pooling in `cloudant-node-sdk`.
no connection pooling bu default
connection pooling bu default with `maxSockets: 6`
=> feat: set keepAlive to true by default

package-lock.json
Fixes vuln for: Minimist <=1.2.5 is vulnerable to Prototype Pollution via file index.js, function setKey() (lines 69-95).
References
- https://nvd.nist.gov/vuln/detail/CVE-2021-44906
- https://github.com/substack/minimist/issues/164
- https://github.com/substack/minimist/blob/master/index.js#L69
- https://snyk.io/vuln/SNYK-JS-MINIMIST-559764
- https://stackoverflow.com/questions/8588563/adding-custom-properties-to-a-function/20278068#20278068
=> buid(deps-dev): fix Minimist vulnerability

lib/cloudantBaseService.ts, test/integration/cloudant.integration.test.js
add missing operation names to path validator
**Note: An existing issue is [required](https://github.com/IBM/cloudant-java-sdk/blob/main/CONTRIBUTING.md#PRs) before opening a PR.**
Not all operations have paths validated
Validate paths additionally on
`getDocumentAsMixed`
`getDocumentAsRelated`
`getDocumentAsStream`
migration path: any applications which use special paths for the above operations should use the correct operation, eg one of the `*AllDocs*` methods in the case of the `_all_docs` path.
=> fix: add missing operation names to path validator

.github/workflows/test.yml, .secrets.baseline, package.json
Just a tiny cleanup. We haven't used travis for a while and not goign back to it, so not reason to keep it in run's target names.
Fixes: #1207 
=> chore: remove travis suffix from package targets

test/unit/features/changesResultIterator.test.js
test: ensure dwell longer than tolerance
To allow for timing instability ensure the dwell time has additional buffer over the error tolerance time.
Intermittent failure was observed in the:
`test/unit/features/changesResultIterator.test.js`
`testNextWithFiniteErrorTolerance`
`with supppresion sequences`
`SUCCESS SUCCESS THROW` case
where the error was not thrown.
Decouple the tolerance time and the dwell time in the test to allow a little more buffer to receive the error.
=> test: ensure dwell longer than tolerance

.github/workflows/docs.yml, .gitignore, package.json
To ensure that we have docs builder working correctly this PR adds a github action that'd run docs build command on pull requests against `main`.
We don't care about difference with `gh-pages` content, so the test is only about ability to successfully run the docs build command itself.
=> ci: add github action to test docs builder

cloudant/features/changesFollower.ts, test/unit/features/changesFollower.test.js
Fixes: #1384
Error tolerance deadline exceeds immediately (as behaves as 0) when `errorTolerance` is set explicitly to `null`.
Error tolerance is set to max (infinity) when `errorTolerance` is set explicitly to `null`.
Use `0` instead of `null` to disable error suppression and terminate changes follower on any failed request as it is documented.
=> fix: set errorTolerance to max when initial value is null

auth/index.ts, cloudant/features/changesFollower.ts, cloudant/features/changesResultIterator.ts, index.ts, package.json, scripts/typedoc/generate_typedoc.sh, typedoc.json
These changes will hide the internal documentation of changes follower from our following published Typedoc.
The locally generated result can be downloaded here: 
[apidocs.zip](https://github.com/IBM/cloudant-node-sdk/files/13950856/apidocs.zip) and can be compared to our [latest published Typedoc](https://ibm.github.io/cloudant-node-sdk/docs/latest/).
=> fix(docs): hide typedoc for internal changes follower code

.secrets.baseline, test/unit/features/testMocks.js
Fix intermittent timeouts in follower UTs.
Fixes: sdks 903
Tests intermittently time out.
Tests are much quicker 
The main thing this change does is avoid generating a ton of random strings that is time consuming. Instead it derives uniqueness from the doc number etc.
Oh and a baseline change, because detect secrets.
=> test: fix intermittent timeouts in follower UTs

api-changes.md
Fixes: #1605 
Doc `0.9.0` migration example incorrectly used `validateDocUpdate`.
Docs `0.9.0`migration example correctly uses `validate_doc_update`.
=> docs: correct parameter name in API change example

.eslintrc.js, .secrets.baseline, auth/sessionTokenManager.ts, cloudant/features/changesFollower.ts, cloudant/features/changesResultItemStream.ts, cloudant/features/changesResultIterator.ts, cloudant/features/stream.ts, index.ts, lib/cloudantBaseService.ts, lib/common.ts, test/examples/src/features/js/initialize.js, test/examples/src/features/js/start.js, test/examples/src/features/js/startAndProcess.js, test/examples/src/features/js/startOneOff.js, test/examples/src/features/js/startOneOffAndProcess.js, test/examples/src/features/js/stop.js, test/unit/cloudantBaseService.test.js, tsconfig.json
This is a build refactoring work that makes sure we are using esm style imports in all of our custom modules and consistently using cjs `required` across tests.
=> build: switch from required to imports in custom lib modules

index.ts
The named import of `CloudantV1` for esm modules was broken in 0.10.2, this patch remediates the degradation 
Fixes: #1631
=> Fix named import of CloudantV1

lib/cloudantBaseService.ts, lib/errorResponseInterceptor.ts, package-lock.json, package.json, test/unit/errorResponseInterceptor.test.js, test/unit/features/testDataProviders.js
Add interceptor for error response augmentation
Fixes: s1003
Cloudant/CouchDB error models are handled by the core with only the `error` field being processed. Obtaining e.g. the `reason` field requires additional user code.
The error response is augmented with `errors` and `trace` properties.
This improves the way the core handles the error response and enhances the user facing exception string to include the `reason`.
The `trace` is the CouchDB request ID which can be used to correlate with logs.
The existing error model fields are retained, the new fields are backwards compatible.
Add …
=> feat: add interceptor for error responses

.secrets.baseline, lib/cloudantBaseService.ts, lib/errorResponseInterceptor.ts, test/unit/errorResponseInterceptor.test.js
Add interceptor for converting streamed error responses to error objects.
Fixes: s1022
For `*AsStrream` endpoint successful responses are returned as `Readable` streams. In the case of an error the error response body is also provided as a `Readable` by the SDK core. This deviates from the behaviour of errors from all other endpoints and prevents the SDK core from, for example, formatting the error response nicely. It also prevents the new improved error responses …
=> feat!: convert stream error responses

.github/workflows/test.yml
Add Node.js `24` to the test matrix
Fixes: part of s1147
No tests on Node.js `24`
Tests on Node.js `24`
Node.js `24` will not be a supported platform for cloudant-node-sdk until it moves to LTS (i.e. Node.js consider it production ready) - this just gets us awareness of any issues on Node.js `24` before that switch in October.
=> ci: add Node.js 24 to test matrix

.github/workflows/static.yml
Update versions of actions in GH pages deployment workflow
Fixes: part of s1192
Actions are not pinned by sha.
Actions are pinned by sha.
=> chore: pin gh-pages actions by sha

.bumpversion.toml, package.json
Update bump version config for docs sub-folder.
Fixes: part of s1173
Version bumps update the main `README` but not the new `docs` sub-folder.
Docs sub-folder is included in version bumping during release.
Tested locally with a dry-run and it looks correct.
=> ci: configure version bump for docs sub-folder

cloudant/features/pagination/basePageIterator.ts
During testing the find pagination feature, it turned out the default limit was not set for the bookmark pagination. This PR intend to fix that bug.
The default limit is not set for the bookmark pagination.
The default limit is set to MAX_LIMIT for the bookmark pagination.
=> fix: add default limit to bookmark pagination
